spring:
  application:
    name: spring-ai-audio
  ai:
    openai:
      base-url: https://api.openai.com
      api-key: your_api_key
      audio:
        speech:
          options:
            #文字转语音
            model: tts-1
            voice: alloy
        transcription:
          options:
            #语音转文字
            model: whisper-1
server:
  port: 8080
# 文本转语音的路径
tts:
  audio-output-dir: /Users/zhangqin/IdeaProjects/new_start_2025/spring-ai/spring-ai-audio/audio-output