spring:
  application:
    name: spring-ai-embedding
  ai:
    zhipuai:
      api-key: 智普AI_API_KEY
      base-url: https://open.bigmodel.cn/api/paas
      embedding:
        options:
          model: embedding-3
          # 向量维度，embedding-3默认的维度是2048
          dimensions: 1024
      chat:
        options:
          model: glm-4.7
server:
  port: 8080