spring:
  application:
    name: spring-ai-ollama
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.8
      embedding:
        options:
          model: nomic-embed-text:latest

server:
  port: 8080
