spring:
  application:
    name: spring-ai-chat-memory-in-memory
  ai:
    deepseek:
      # deepseek的API_KEY
      api-key: deepseek的API_KEY
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

  server:
    port: 8080