spring:
  application:
    name: spring-ai-quickstart
  ai:
    deepseek:
      api-key: sk-364eda7e38ec4c31bca52968bb0bca7f
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          #????0~2?0????????2???????
          temperature: 0.8

server:
  port: 8080
