spring:
  application:
    name: spring-ai-tool-calling
  ai:
    deepseek:
      #deepseek的API_KEY
      api-key: deepseek的API_KEY
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          # 介于0和2之间，0表示随机性最小，2表示随机性最大。
          temperature: 0.8

server:
  port: 8080