spring:
  application:
    name: spring-ai-mcp-stdio-client
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: deepseekçš„API_KEY
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-server-config.json
server:
  port: 8080

logging:
  pattern:
    console: "%-5level %logger - %msg%n"
