spring:
  application:
    name: spring-ai-mcp-sse-client
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: deepseek的API_KEY
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        # SSE模式，配置MCP server的远程服务器地址
        sse:
          connections:
            server1:
              url: http://localhost:8087
server:
  port: 8080

logging:
  pattern:
    console: "%-5level %logger - %msg%n"
